#!/bin/bash

set -Eeu -o pipefail

IMAGE_NAME="caddy"
REPOSITORY="ghcr.io/moritzheiber"
GIT_BRANCH=$(git branch --show-current)
TARGET="latest"
REV=$(git rev-parse --short HEAD)

if ! [ "${GIT_BRANCH}" == "main" ]; then
  TARGET="${GIT_BRANCH:-${REV}}"
fi

CONTAINER="${IMAGE_NAME}:${TARGET}"
export CONTAINER

_ensure_bundle() {
  bundle config set --local path vendor/bundle
  bundle install
}

build() {
  docker build -t "${CONTAINER}" .

  docker tag "${CONTAINER}" "${REPOSITORY}/${CONTAINER}"
  docker tag "${CONTAINER}" "${REPOSITORY}/${IMAGE_NAME}:${REV}"
}

push() {
  docker push "${REPOSITORY}/${CONTAINER}"
  docker push "${REPOSITORY}/${IMAGE_NAME}:${REV}"
}

_test() {
  _ensure_bundle
  bundle exec rspec
}

usage() {
  echo "Usage ${0} build | test | push"
  exit 1
}

CMD=${1:-}
shift || true
case ${CMD} in
build) build ;;
test) _test ;;
push) push ;;
*) usage ;;
esac
